version: "3.3"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Standard"
      SA_PASSWORD: "yourStrong(!)Password"
